# Site settings

title: 'alfdavsec'
description: "alfdav ramblings site."
url: "https://alfdav.github.io"

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md

footer: 'follow me on <a href="https://twitter.com/">twitter</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
  
remote_theme: b2a3e8/jekyll-theme-console

